# Generated by Django 5.1.15 on 2026-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='image_url',
        ),
        migrations.AddField(
            model_name='closet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='closet_images/'),
        ),
    ]
