# Generated by Django 5.1.15 on 2026-02-12 01:22

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '00003_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AddField(
            model_name='closet',
            name='style_cat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='스타일 카테고리'),
        ),
    ]
