# Generated by Django 5.1.15 on 2026-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musinsa_product_id', models.CharField(help_text='무신사 상품 ID (외부 식별자)', max_length=50, unique=True)),
                ('category_main', models.CharField(db_index=True, max_length=30)),
                ('category_sub', models.CharField(db_index=True, max_length=30)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='상품 가격 (원 단위)')),
                ('product_url', models.URLField(max_length=500)),
                ('product_image_path', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category_main', 'category_sub'], name='products_categor_00b13d_idx')],
            },
        ),
    ]
