# Generated by Django 5.1.15 on 2026-02-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='musinsa_product_id',
        ),
    ]
