# Generated by Django 5.1.15 on 2026-02-19 06:14

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_musinsa_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('style_cat', models.CharField(db_index=True, max_length=50)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reference_embeddings',
            },
        ),
    ]
