# Generated by Django 5.1.15 on 2026-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_referenceembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
